name: Reusable Notification Workflow

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:

  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: jeanmn/github-actions/actions/notify-on-fail-or-fix@main
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
